#!/bin/bash
# First we subset the vcf to individual from a specific population
#Then we get the allele count for each site. If it is 0 it means than this ALT allele is missing in the subsetted vcf individuals
#There can be several ALT allele, their count are separated by comma (ex: 0,0 or 0,1 or 0,1,0), so if we remove comma, sites that are fully reference (not a SNP within these individuals) will be as a sequence of zeros
#We remove sequences of zeros (constant site equal to the reference), by taking merged (by removing commas) allele count higher than zero
#We count the number of lines left
bcftools view -S cheese2snp_pass.vcf.gz|bcftools query -f '%AC\n'|sed 's/,//g' |awk '$1>=1'| wc -l
